version: '3.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - db-vol:/var/lib/postgresql/data
    networks:
      - infra
  back:
    image: es2/back
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - infra
volumes:
  db-vol:

networks:
  infra:
    driver: bridge
